# Generated by Django 2.1.5 on 2019-09-28 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('img', models.ImageField(default='imagenes/no-image.png', upload_to='imagenes')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.BooleanField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_item', to='inventory.Item')),
            ],
        ),
    ]
