# Generated by Django 2.1.5 on 2019-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='imagenes/no-image.jpg', upload_to='imagenes'),
        ),
    ]
