# Generated by Django 2.1.5 on 2019-09-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190908_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
