# Generated by Django 2.1.5 on 2019-09-10 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
    ]
